version: '2'
services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d # лучше подключить деррикторию с конфигами чем один файл
      - ./www:/var/www
      - ./logs:/var/log/nginx/
    links:
      - php

  php:
    build: ./images/php
    links:
      - mysql
    volumes:
      - ./www:/var/www

  mysql:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #command: --default-authentication-plugin=mysql_native_password

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root