version: '3'

services:

  proxy:
    container_name: nginx_proxy
    image: nginx:latest # this will use the latest version of 1.11.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/var/www/html/index.html
      #- ./nginx/index.php:/var/www/html/index.php
    depends_on:
      - apache2

  apache2:
    container_name: apache2
    build: .
    volumes:
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2/index.php:/var/www/html/index.php
      - ./apache2/test.php:/var/www/html/test.php


