version: '3'

services:

  proxy:
    container_name: nginx_proxy
    image: nginx:latest # this will use the latest version of 1.11.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www/project/:/var/www/html/
    depends_on:
      - apache2
    networks:
      - default

  apache2:
    container_name: apache2
    build: .
    volumes:
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./www/project/:/var/www/html/
    links:
      - db:mariadb
    depends_on:
      - db
    networks:
      - default
# при выполнении скриптов взаимодействующих с базой       
# часто возникала ошибка access denied for root@ip container apache 
# пришлось залезать в контейнер мускула и добавлять root@ip этого контейнера
# что не есть хорошо все должно работать при запуске контейнеров ...
# Не самое лучшее решение сделать docker commit для мускул контейнера после внесения изменений
# для пересборки используй docker-compose up --build
  db:
    image: mariadb:10.1.45
    container_name: mariadb
    #restart: always
    environment:
      #MYSQL_DATABASE: publications
      #MYSQL_USER: root
      #MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      #MYSQL_ROOT_HOST: apache2
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql/:/var/lib/mysql # add data mysql
      - /home/vadim/docker/Git_repo/apache2_with_nginx2/www/project/curse2/eshop/eshop.sql:/tmp/eshop.sql
    #volumes:
     # - /var/lib/mysql/:/var/lib/mysql # add data mysql
    networks:
      - default
      
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
