version: '3'

services:

  proxy:
    container_name: nginx_proxy
    image: nginx:latest # this will use the latest version of 1.11.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/var/www/html/index.html
    depends_on:
      - apache2
    networks:
      - default

  apache2:
    container_name: apache2
    build: .
    volumes:
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /var/www/php/:/var/www/html/
    links:
      - db:mysql
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: publications
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql # add data mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
  networks:
    - default